---

- name: Copy basic exporter script
  ansible.builtin.template:
    src: "basic_exporter"
    dest: /usr/local/bin/basic_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy basic exporter script
  ansible.builtin.template:
    src: "basic_exporter.service"
    dest: /etc/systemd/system/basic_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart basic exporter service is restarted
  ansible.builtin.service:
    name: Basic_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for basic exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ basic_exporter_server_bind }}"
    port: "{{ basic_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
