---
# handlers for ansible-role-docker-basic_exporter

- name: Restart basic_exporter
  ansible.builtin.service:
    name: Basic_exporter
    state: restarted
    enabled: true

- name: Start basic_exporter
  ansible.builtin.service:
    name: Basic_exporter
    state: started
    enabled: true

- name: Reload basic_exporter
  ansible.builtin.service:
    name: Basic_exporter
    state: reloaded
    enabled: true
